default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: tfbase
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: tfbase_development

test:
  <<: *default
  database: tfbase_test

production:
  <<: *default
  database: tfbase_production
  username: rails
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
